== CPO 16 - Activity Report - November 2017
Tracey Birch <tracey.birch@sofwerx.org> +
14 December 2017

==== Software

- Configured a dedicated server for distributed, virtual geospatial experimentation & testing

- Researched, obtained, and installed open source GIS software on server

- Obtained extension for Luciad Fusion Server development license

- Installed ATAK and GO ISP on mobile Android devices

- Researched procedures for loading GeoPackage map data onto mobile device apps

- Worked with USSOCOM & UTB personnel to resolve problems with accessing map data at UTB over VPN


==== Open Standards / OGC

- Reviewed changes to Related Tables Extension proposed standard and prepared feedback for SWG discussion

- Participated in OGC (Open Geospatial Consortium) GeoPackage SWG (Standards Working Group) meetings (telcons) and online discussions

- Participated in OGC Related Tables Extension Interoperability Experiment telcons and online discussions

- Discussed potential collaboration with "Geospatial to the Edge" plugfest during our April geospatial event - telcons with Luis Bermudez, OGC Executive Director Innovation Program

==== Events

- Prepared presentation on current & future SOFWERX GeoPackage efforts

- Attended 3D GeoPackage IPR 15 Nov

- Presented SOFWERX/USSOCOM GeoPackage efforts at OGC Geospatial 3D M&S Summit II during I/ITSEC conference 29 Nov

==== Other

- Had several informal discussions with warfighters to better understand their needs wrt geospatial capabilities

- Obtined CAD files of SOFWERX Underground building in preparation for ISP collect scheduled for January January

